version: '3.8'

services:
  db:
    image: postgres:13
    environment:
      POSTGRES_DB: trail_app
      POSTGRES_USER: green_leaf
      POSTGRES_PASSWORD: green_leaf
      POSTGRES_HOST_AUTH_METHOD: trust
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
      - ./pg_hba.conf:/etc/postgresql/13/main/pg_hba.conf

  migrations:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      DB_HOST: db
      DB_USER: green_leaf
      DB_PASS: green_leaf
      DB_NAME: trail_app
    working_dir: /app/database
    depends_on:
      - db
    command: ["sh", "-c", "alembic revision --autogenerate -m 'Auto migration' && alembic upgrade head"]

volumes:
  db_data:
